/**
 * 3Blades API
 * This is 3Blades's API.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@3blades.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.3BladesApi) {
      root.3BladesApi = {};
    }
    root.3BladesApi.EnvType = factory(root.3BladesApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EnvType model module.
   * @module model/EnvType
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>EnvType</code>.
   * @alias module:model/EnvType
   * @class
   * @param name {String} 
   * @param imageName {String} 
   * @param CMD {String} 
   */
  var exports = function(name, imageName, CMD) {
    var _this = this;


    _this['name'] = name;
    _this['imageName'] = imageName;
    _this['CMD'] = CMD;
  };

  /**
   * Constructs a <code>EnvType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EnvType} obj Optional instance to populate.
   * @return {module:model/EnvType} The populated <code>EnvType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('envTypeId')) {
        obj['envTypeId'] = ApiClient.convertToType(data['envTypeId'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('imageName')) {
        obj['imageName'] = ApiClient.convertToType(data['imageName'], 'String');
      }
      if (data.hasOwnProperty('CMD')) {
        obj['CMD'] = ApiClient.convertToType(data['CMD'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} envTypeId
   */
  exports.prototype['envTypeId'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} imageName
   */
  exports.prototype['imageName'] = undefined;
  /**
   * @member {String} CMD
   */
  exports.prototype['CMD'] = undefined;



  return exports;
}));


