/**
 * 3Blades API
 * This is 3Blades's API.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@3blades.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.3BladesApi) {
      root.3BladesApi = {};
    }
    root.3BladesApi.Model = factory(root.3BladesApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Model model module.
   * @module model/Model
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Model</code>.
   * @alias module:model/Model
   * @class
   * @param script {String} 
   * @param method {String} 
   */
  var exports = function(script, method) {
    var _this = this;


    _this['script'] = script;
    _this['method'] = method;
  };

  /**
   * Constructs a <code>Model</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Model} obj Optional instance to populate.
   * @return {module:model/Model} The populated <code>Model</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('server_id')) {
        obj['server_id'] = ApiClient.convertToType(data['server_id'], 'String');
      }
      if (data.hasOwnProperty('script')) {
        obj['script'] = ApiClient.convertToType(data['script'], 'String');
      }
      if (data.hasOwnProperty('method')) {
        obj['method'] = ApiClient.convertToType(data['method'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} server_id
   */
  exports.prototype['server_id'] = undefined;
  /**
   * @member {String} script
   */
  exports.prototype['script'] = undefined;
  /**
   * @member {String} method
   */
  exports.prototype['method'] = undefined;



  return exports;
}));


