/**
 * 3Blades API
 * This is 3Blades's API.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@3blades.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EnvType', 'model/ResourcesType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EnvType'), require('./ResourcesType'));
  } else {
    // Browser globals (root is window)
    if (!root.3BladesApi) {
      root.3BladesApi = {};
    }
    root.3BladesApi.Server = factory(root.3BladesApi.ApiClient, root.3BladesApi.EnvType, root.3BladesApi.ResourcesType);
  }
}(this, function(ApiClient, EnvType, ResourcesType) {
  'use strict';




  /**
   * The Server model module.
   * @module model/Server
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Server</code>.
   * @alias module:model/Server
   * @class
   * @param name {String} 
   * @param envTypeId {module:model/EnvType} 
   * @param resourcesId {module:model/ResourcesType} 
   */
  var exports = function(name, envTypeId, resourcesId) {
    var _this = this;

    _this['name'] = name;
    _this['envTypeId'] = envTypeId;
    _this['resourcesId'] = resourcesId;
  };

  /**
   * Constructs a <code>Server</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Server} obj Optional instance to populate.
   * @return {module:model/Server} The populated <code>Server</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('envTypeId')) {
        obj['envTypeId'] = EnvType.constructFromObject(data['envTypeId']);
      }
      if (data.hasOwnProperty('resourcesId')) {
        obj['resourcesId'] = ResourcesType.constructFromObject(data['resourcesId']);
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/EnvType} envTypeId
   */
  exports.prototype['envTypeId'] = undefined;
  /**
   * @member {module:model/ResourcesType} resourcesId
   */
  exports.prototype['resourcesId'] = undefined;



  return exports;
}));


